<h1> FORM TICKET </h1>
<form action="<?php echo $block->getUrl('customdb/page/insertform');?>" method="post" enctype="multipart/form-data">
  <?php echo $this->getBlockHtml('insertformkey')?> <!-- chiave nascosta per cross origin request -->
  <label for="fname">NOME:</label><br>
  <input type="text" id="nome" name="nome" value="enrico"><br>
  <label for="lsurname">COGNOME:</label><br>
  <input type="text" id="cognome" name="cognome" value="giorgi"><br>
  <label for="ticket">TICKET ID:</label><br>
  <input type="number" id="ticketid" name="ticketid" ><br>
    <label for="email">EMAIl:</label><br>
    <input type="text" id="email" name="email" ><br>
  <button type="submit" name="send" value="insert"> insert </button>
  <button>
      <a href="<?php echo $block->getUrl('customdb/page/ticket/');?>">HOME</a>
  </button>
</form>





