<h2>TICKETS SECTION</h2>
<?php
$result = $block->getData('tickets');


?>
<table >
<?php foreach($result as $ticket) { ?>
  <tr>
    <th ><?php echo $ticket->getData('number_id'); ?> </th>
    <th><?php  echo $ticket->getNome();  ?></th>
    <th><?php  echo $ticket->getCognome();   ?></th>
    <th><?php  echo $ticket->getTicketid();   ?></th>

    <th><a href="<?php echo $block->getUrl('customdb/page/insertform');?>">INSERT</a></th>
    <th><a href="<?php echo $block->getUrl('customdb/page/updateform/');?>">UPDATE</a></th>
    <th><a href="<?php echo $block->getUrl('customdb/page/deleteform/');?>">DELETE</a></th>
  </tr>
 <?php } ?>
</table>
