<h2>TICKETS SECTION</h2>
<?php
$result = $block->getData('tickets');

?>
<table>
    <tr>
        <th>NUMBER ID:</th>
        <th>NOME:</th>
        <th>COGNOME:</th>
        <th>TICKET ID:</th>
        <th>EMAIL:</th>
    </tr>
    <?php foreach ($result as $ticket) { ?>

        <tr>
            <td><?php echo $ticket->getData('number_id'); ?> </td>
            <td><?php echo $ticket->getNome(); ?></td>
            <td><?php echo $ticket->getCognome(); ?></td>
            <td><?php echo $ticket->getTicketid(); ?></td>
            <td><?php echo $ticket->getEmail(); ?></td>

            <td><a href="<?php echo $block->getUrl('customdb/page/insertform'); ?>">INSERT</a></td>
            <td>
                <a href="<?php echo $block->getUrl('customdb/page/updateform', ['number_id' => $ticket->getData('number_id')]) ?>">UPDATE</a></td>

            <td><a href="<?php echo $block->getUrl('customdb/page/deleteform/'); ?>">DELETE</a></td>
        </tr>
    <?php } ?>
</table>
